<a href="https://colab.research.google.com/github/rubiiinnn/machine-_Learning/blob/main/pandaBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
#Dataset load krna

In [ ]:
#file upload krne ka tareeqa
from google.colab import files

files.upload()

Saving Iris.csv to Iris (1).csv

{'Iris (1).csv': b'Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species\n1,5.1,3.5,1.4,0.2,Iris-setosa\n2,4.9,3.0,1.4,0.2,Iris-setosa\n3,4.7,3.2,1.3,0.2,Iris-setosa\n4,4.6,3.1,1.5,0.2,Iris-setosa\n5,5.0,3.6,1.4,0.2,Iris-setosa\n6,5.4,3.9,1.7,0.4,Iris-setosa\n7,4.6,3.4,1.4,0.3,Iris-setosa\n8,5.0,3.4,1.5,0.2,Iris-setosa\n9,4.4,2.9,1.4,0.2,Iris-setosa\n10,4.9,3.1,1.5,0.1,Iris-setosa\n11,5.4,3.7,1.5,0.2,Iris-setosa\n12,4.8,3.4,1.6,0.2,Iris-setosa\n13,4.8,3.0,1.4,0.1,Iris-setosa\n14,4.3,3.0,1.1,0.1,Iris-setosa\n15,5.8,4.0,1.2,0.2,Iris-setosa\n16,5.7,4.4,1.5,0.4,Iris-setosa\n17,5.4,3.9,1.3,0.4,Iris-setosa\n18,5.1,3.5,1.4,0.3,Iris-setosa\n19,5.7,3.8,1.7,0.3,Iris-setosa\n20,5.1,3.8,1.5,0.3,Iris-setosa\n21,5.4,3.4,1.7,0.2,Iris-setosa\n22,5.1,3.7,1.5,0.4,Iris-setosa\n23,4.6,3.6,1.0,0.2,Iris-setosa\n24,5.1,3.3,1.7,0.5,Iris-setosa\n25,4.8,3.4,1.9,0.2,Iris-setosa\n26,5.0,3.0,1.6,0.2,Iris-setosa\n27,5.0,3.4,1.6,0.4,Iris-setosa\n28,5.2,3.5,1.5,0.2,Iris-setosa\n29,5.2,3.4,1.4,0.2,Iris-setosa\n30,4.7,3.2,1.6,0.2,Iris-setosa\n31,4.8,3.1,1.6,0.2,Iris-setosa\n32,5.4,3.4,1.5,0.4,Iris-setosa\n33,5.2,4.1,1.5,0.1,Iris-setosa\n34,5.5,4.2,1.4,0.2,Iris-setosa\n35,4.9,3.1,1.5,0.1,Iris-setosa\n36,5.0,3.2,1.2,0.2,Iris-setosa\n37,5.5,3.5,1.3,0.2,Iris-setosa\n38,4.9,3.1,1.5,0.1,Iris-setosa\n39,4.4,3.0,1.3,0.2,Iris-setosa\n40,5.1,3.4,1.5,0.2,Iris-setosa\n41,5.0,3.5,1.3,0.3,Iris-setosa\n42,4.5,2.3,1.3,0.3,Iris-setosa\n43,4.4,3.2,1.3,0.2,Iris-setosa\n44,5.0,3.5,1.6,0.6,Iris-setosa\n45,5.1,3.8,1.9,0.4,Iris-setosa\n46,4.8,3.0,1.4,0.3,Iris-setosa\n47,5.1,3.8,1.6,0.2,Iris-setosa\n48,4.6,3.2,1.4,0.2,Iris-setosa\n49,5.3,3.7,1.5,0.2,Iris-setosa\n50,5.0,3.3,1.4,0.2,Iris-setosa\n51,7.0,3.2,4.7,1.4,Iris-versicolor\n52,6.4,3.2,4.5,1.5,Iris-versicolor\n53,6.9,3.1,4.9,1.5,Iris-versicolor\n54,5.5,2.3,4.0,1.3,Iris-versicolor\n55,6.5,2.8,4.6,1.5,Iris-versicolor\n56,5.7,2.8,4.5,1.3,Iris-versicolor\n57,6.3,3.3,4.7,1.6,Iris-versicolor\n58,4.9,2.4,3.3,1.0,Iris-versicolor\n59,6.6,2.9,4.6,1.3,Iris-versicolor\n60,5.2,2.7,3.9,1.4,Iris-versicolor\n61,5.0,2.0,3.5,1.0,Iris-versicolor\n62,5.9,3.0,4.2,1.5,Iris-versicolor\n63,6.0,2.2,4.0,1.0,Iris-versicolor\n64,6.1,2.9,4.7,1.4,Iris-versicolor\n65,5.6,2.9,3.6,1.3,Iris-versicolor\n66,6.7,3.1,4.4,1.4,Iris-versicolor\n67,5.6,3.0,4.5,1.5,Iris-versicolor\n68,5.8,2.7,4.1,1.0,Iris-versicolor\n69,6.2,2.2,4.5,1.5,Iris-versicolor\n70,5.6,2.5,3.9,1.1,Iris-versicolor\n71,5.9,3.2,4.8,1.8,Iris-versicolor\n72,6.1,2.8,4.0,1.3,Iris-versicolor\n73,6.3,2.5,4.9,1.5,Iris-versicolor\n74,6.1,2.8,4.7,1.2,Iris-versicolor\n75,6.4,2.9,4.3,1.3,Iris-versicolor\n76,6.6,3.0,4.4,1.4,Iris-versicolor\n77,6.8,2.8,4.8,1.4,Iris-versicolor\n78,6.7,3.0,5.0,1.7,Iris-versicolor\n79,6.0,2.9,4.5,1.5,Iris-versicolor\n80,5.7,2.6,3.5,1.0,Iris-versicolor\n81,5.5,2.4,3.8,1.1,Iris-versicolor\n82,5.5,2.4,3.7,1.0,Iris-versicolor\n83,5.8,2.7,3.9,1.2,Iris-versicolor\n84,6.0,2.7,5.1,1.6,Iris-versicolor\n85,5.4,3.0,4.5,1.5,Iris-versicolor\n86,6.0,3.4,4.5,1.6,Iris-versicolor\n87,6.7,3.1,4.7,1.5,Iris-versicolor\n88,6.3,2.3,4.4,1.3,Iris-versicolor\n89,5.6,3.0,4.1,1.3,Iris-versicolor\n90,5.5,2.5,4.0,1.3,Iris-versicolor\n91,5.5,2.6,4.4,1.2,Iris-versicolor\n92,6.1,3.0,4.6,1.4,Iris-versicolor\n93,5.8,2.6,4.0,1.2,Iris-versicolor\n94,5.0,2.3,3.3,1.0,Iris-versicolor\n95,5.6,2.7,4.2,1.3,Iris-versicolor\n96,5.7,3.0,4.2,1.2,Iris-versicolor\n97,5.7,2.9,4.2,1.3,Iris-versicolor\n98,6.2,2.9,4.3,1.3,Iris-versicolor\n99,5.1,2.5,3.0,1.1,Iris-versicolor\n100,5.7,2.8,4.1,1.3,Iris-versicolor\n101,6.3,3.3,6.0,2.5,Iris-virginica\n102,5.8,2.7,5.1,1.9,Iris-virginica\n103,7.1,3.0,5.9,2.1,Iris-virginica\n104,6.3,2.9,5.6,1.8,Iris-virginica\n105,6.5,3.0,5.8,2.2,Iris-virginica\n106,7.6,3.0,6.6,2.1,Iris-virginica\n107,4.9,2.5,4.5,1.7,Iris-virginica\n108,7.3,2.9,6.3,1.8,Iris-virginica\n109,6.7,2.5,5.8,1.8,Iris-virginica\n110,7.2,3.6,6.1,2.5,Iris-virginica\n111,6.5,3.2,5.1,2.0,Iris-virginica\n112,6.4,2.7,5.3,1.9,Iris-virginica\n113,6.8,3.0,5.5,2.1,Iris-virginica\n114,5.7,2.5,5.0,2.0,Iris-virginica\n115,5.8,2.8,5.1,2.4,Iris-virginica\n116,6.4,3.2,5.3,2.3,Iris-virginica\n117,6.5,3.0,5.5,1.8,Iris-virginica\n118,7.7,3.8,6.7,2.2,Iris-virginica\n119,7.7,2.6,6.9,2.3,Iris-virginica\n120,6.0,2.2,5.0,1.5,Iris-virginica\n121,6.9,3.2,5.7,2.3,Iris-virginica\n122,5.6,2.8,4.9,2.0,Iris-virginica\n123,7.7,2.8,6.7,2.0,Iris-virginica\n124,6.3,2.7,4.9,1.8,Iris-virginica\n125,6.7,3.3,5.7,2.1,Iris-virginica\n126,7.2,3.2,6.0,1.8,Iris-virginica\n127,6.2,2.8,4.8,1.8,Iris-virginica\n128,6.1,3.0,4.9,1.8,Iris-virginica\n129,6.4,2.8,5.6,2.1,Iris-virginica\n130,7.2,3.0,5.8,1.6,Iris-virginica\n131,7.4,2.8,6.1,1.9,Iris-virginica\n132,7.9,3.8,6.4,2.0,Iris-virginica\n133,6.4,2.8,5.6,2.2,Iris-virginica\n134,6.3,2.8,5.1,1.5,Iris-virginica\n135,6.1,2.6,5.6,1.4,Iris-virginica\n136,7.7,3.0,6.1,2.3,Iris-virginica\n137,6.3,3.4,5.6,2.4,Iris-virginica\n138,6.4,3.1,5.5,1.8,Iris-virginica\n139,6.0,3.0,4.8,1.8,Iris-virginica\n140,6.9,3.1,5.4,2.1,Iris-virginica\n141,6.7,3.1,5.6,2.4,Iris-virginica\n142,6.9,3.1,5.1,2.3,Iris-virginica\n143,5.8,2.7,5.1,1.9,Iris-virginica\n144,6.8,3.2,5.9,2.3,Iris-virginica\n145,6.7,3.3,5.7,2.5,Iris-virginica\n146,6.7,3.0,5.2,2.3,Iris-virginica\n147,6.3,2.5,5.0,1.9,Iris-virginica\n148,6.5,3.0,5.2,2.0,Iris-virginica\n149,6.2,3.4,5.4,2.3,Iris-virginica\n150,5.9,3.0,5.1,1.8,Iris-virginica\n'}

In [ ]:
df = pd.read_csv("Iris.csv") #df = datframe like a table

In [ ]:
#CHECK YOUR DATA SBSE PEHLE

In [ ]:
df.head()     #first 5 rows
df.shape      # Rows, Columns
df.info()     # Data type + missing values
df.describe() # Math summary

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [ ]:
#check for missing values - ye bhi important step hai
# agr missing value hai to model ache se kam nai krta - error deta hai

In [ ]:
df.isnull().sum()  #humare dataset mai koi missing value nai hai

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [ ]:
#if there is missing value
# 1) missing data vali rows ko dlt krdo - df.dropna(inplace=True) - kam dataset ke liye hi sahi hai bs ,ML ki accuracy gir skti

#2)0 se fill krdo - df.fillna(0, inplace=True) - can give glt result

#3) Mean se fill krna - df["Age"].mean() - mean calculate kro
#                       df["Age"].fillna(df["Age"].mean(), inplace=True) - fill krdo
#                       df["Age"].fillna(df["Age"].mean(), inplace=True)

#4) MODE (text data ke liye) - zyada occurence vo data fill in the missing places
#                             df["City"].fillna(df["City"].mode()[0], inplace=True)

In [ ]:
#ENCODING - Text data ko number mai
# Speciies - oobject hai - inhe number mai kro

In [ ]:
df = pd.get_dummies(df, drop_first=True)

In [ ]:
#Dlt useless column - id use ki nai usko htaa do

In [ ]:
df.drop("Id", axis=1, inplace=True)

In [ ]:
#INPUT (x) & OUTPUT (y)
# hum species predict krna chate hai - output
#  df.iloc[ rows , columns ] - jab Tumhara target column last me ho use this

In [ ]:
X = df.iloc[:, :-1] #Saari rows ,  Last column ko chhod ke baaki sab columns
y = df.iloc[:, -1]

In [ ]:
#check final data

In [ ]:
print(X.shape)
print(y.shape)

(150, 5)
(150,)